<?php
/**
 * CreatePayment
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  TheLogicStudio\ExactPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Embedded Payments
 *
 * Embedding payments into your software platform can be one of the most powerful value drivers for your customers and your top line. Imagine your software delivering the entire order-to-cash cycle including funding right into the customer’s bank account. We provide low code integration- With just a single API, you can go live with Exact Payments. Onboard customers, automated underwriting, receive webhook notifications when your customers is live and ready to take payments. We have all the payment types your customers want and their buyers need. Credit and debit cards plus ACH payments, Apple Pay, Google Pay, Paypal, recurring payments, card-on-file and more. Dive into our API Reference and add embedded payments with Exact today!
 *
 * The version of the OpenAPI document: 1.0.4
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TheLogicStudio\ExactPay\Foofoo;

use \ArrayAccess;
use \TheLogicStudio\ExactPay\ObjectSerializer;

/**
 * CreatePayment Class Doc Comment
 *
 * @category Class
 * @package  TheLogicStudio\ExactPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreatePayment implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreatePayment';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'amount' => 'int',
        'surcharge_amount' => 'int',
        'tax_amount' => 'int',
        'capture' => 'bool',
        'payment_method' => '\TheLogicStudio\ExactPay\Foofoo\PaymentMethodChoice',
        'customer' => '\TheLogicStudio\ExactPay\Foofoo\BillingCustomer',
        'reference' => '\TheLogicStudio\ExactPay\Foofoo\Reference',
        'stored_credentials' => '\TheLogicStudio\ExactPay\Foofoo\StoredCredentials',
        'soft_descriptor' => '\TheLogicStudio\ExactPay\Foofoo\SoftDescriptor',
        'level3' => '\TheLogicStudio\ExactPay\Foofoo\Level3',
        'three_d_secure' => '\TheLogicStudio\ExactPay\Foofoo\ThreeDSecure',
        'options' => '\TheLogicStudio\ExactPay\Foofoo\PaymentOptions'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'amount' => 'int32',
        'surcharge_amount' => 'int32',
        'tax_amount' => 'uint32',
        'capture' => null,
        'payment_method' => null,
        'customer' => null,
        'reference' => null,
        'stored_credentials' => null,
        'soft_descriptor' => null,
        'level3' => null,
        'three_d_secure' => null,
        'options' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'amount' => false,
		'surcharge_amount' => false,
		'tax_amount' => false,
		'capture' => false,
		'payment_method' => false,
		'customer' => false,
		'reference' => false,
		'stored_credentials' => false,
		'soft_descriptor' => false,
		'level3' => false,
		'three_d_secure' => false,
		'options' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'amount' => 'amount',
        'surcharge_amount' => 'surchargeAmount',
        'tax_amount' => 'taxAmount',
        'capture' => 'capture',
        'payment_method' => 'paymentMethod',
        'customer' => 'customer',
        'reference' => 'reference',
        'stored_credentials' => 'storedCredentials',
        'soft_descriptor' => 'softDescriptor',
        'level3' => 'level3',
        'three_d_secure' => 'threeDSecure',
        'options' => 'options'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'amount' => 'setAmount',
        'surcharge_amount' => 'setSurchargeAmount',
        'tax_amount' => 'setTaxAmount',
        'capture' => 'setCapture',
        'payment_method' => 'setPaymentMethod',
        'customer' => 'setCustomer',
        'reference' => 'setReference',
        'stored_credentials' => 'setStoredCredentials',
        'soft_descriptor' => 'setSoftDescriptor',
        'level3' => 'setLevel3',
        'three_d_secure' => 'setThreeDSecure',
        'options' => 'setOptions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'amount' => 'getAmount',
        'surcharge_amount' => 'getSurchargeAmount',
        'tax_amount' => 'getTaxAmount',
        'capture' => 'getCapture',
        'payment_method' => 'getPaymentMethod',
        'customer' => 'getCustomer',
        'reference' => 'getReference',
        'stored_credentials' => 'getStoredCredentials',
        'soft_descriptor' => 'getSoftDescriptor',
        'level3' => 'getLevel3',
        'three_d_secure' => 'getThreeDSecure',
        'options' => 'getOptions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('surcharge_amount', $data ?? [], null);
        $this->setIfExists('tax_amount', $data ?? [], null);
        $this->setIfExists('capture', $data ?? [], null);
        $this->setIfExists('payment_method', $data ?? [], null);
        $this->setIfExists('customer', $data ?? [], null);
        $this->setIfExists('reference', $data ?? [], null);
        $this->setIfExists('stored_credentials', $data ?? [], null);
        $this->setIfExists('soft_descriptor', $data ?? [], null);
        $this->setIfExists('level3', $data ?? [], null);
        $this->setIfExists('three_d_secure', $data ?? [], null);
        $this->setIfExists('options', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['amount'] === null) {
            $invalidProperties[] = "'amount' can't be null";
        }
        if (($this->container['amount'] > 999999999)) {
            $invalidProperties[] = "invalid value for 'amount', must be smaller than or equal to 999999999.";
        }

        if (($this->container['amount'] < 0)) {
            $invalidProperties[] = "invalid value for 'amount', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['surcharge_amount']) && ($this->container['surcharge_amount'] > 999999999)) {
            $invalidProperties[] = "invalid value for 'surcharge_amount', must be smaller than or equal to 999999999.";
        }

        if (!is_null($this->container['surcharge_amount']) && ($this->container['surcharge_amount'] < 0)) {
            $invalidProperties[] = "invalid value for 'surcharge_amount', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['tax_amount']) && ($this->container['tax_amount'] > 999999999)) {
            $invalidProperties[] = "invalid value for 'tax_amount', must be smaller than or equal to 999999999.";
        }

        if (!is_null($this->container['tax_amount']) && ($this->container['tax_amount'] < 0)) {
            $invalidProperties[] = "invalid value for 'tax_amount', must be bigger than or equal to 0.";
        }

        if ($this->container['payment_method'] === null) {
            $invalidProperties[] = "'payment_method' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets amount
     *
     * @return int
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param int $amount Total amount including all surcharges, taxes etc. in smallest currency unit, for example, in cents.
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }

        if (($amount > 999999999)) {
            throw new \InvalidArgumentException('invalid value for $amount when calling CreatePayment., must be smaller than or equal to 999999999.');
        }
        if (($amount < 0)) {
            throw new \InvalidArgumentException('invalid value for $amount when calling CreatePayment., must be bigger than or equal to 0.');
        }

        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets surcharge_amount
     *
     * @return int|null
     */
    public function getSurchargeAmount()
    {
        return $this->container['surcharge_amount'];
    }

    /**
     * Sets surcharge_amount
     *
     * @param int|null $surcharge_amount Surcharge amount, in smallest currency unit, for example, in cents. This is assumed to already be included in the amount.
     *
     * @return self
     */
    public function setSurchargeAmount($surcharge_amount)
    {
        if (is_null($surcharge_amount)) {
            throw new \InvalidArgumentException('non-nullable surcharge_amount cannot be null');
        }

        if (($surcharge_amount > 999999999)) {
            throw new \InvalidArgumentException('invalid value for $surcharge_amount when calling CreatePayment., must be smaller than or equal to 999999999.');
        }
        if (($surcharge_amount < 0)) {
            throw new \InvalidArgumentException('invalid value for $surcharge_amount when calling CreatePayment., must be bigger than or equal to 0.');
        }

        $this->container['surcharge_amount'] = $surcharge_amount;

        return $this;
    }

    /**
     * Gets tax_amount
     *
     * @return int|null
     */
    public function getTaxAmount()
    {
        return $this->container['tax_amount'];
    }

    /**
     * Sets tax_amount
     *
     * @param int|null $tax_amount Level 2 tax value, included in total amount, in smallest currency units, for example, in cents in USD. Sales tax in the US, or PST for Canadian merchants.
     *
     * @return self
     */
    public function setTaxAmount($tax_amount)
    {
        if (is_null($tax_amount)) {
            throw new \InvalidArgumentException('non-nullable tax_amount cannot be null');
        }

        if (($tax_amount > 999999999)) {
            throw new \InvalidArgumentException('invalid value for $tax_amount when calling CreatePayment., must be smaller than or equal to 999999999.');
        }
        if (($tax_amount < 0)) {
            throw new \InvalidArgumentException('invalid value for $tax_amount when calling CreatePayment., must be bigger than or equal to 0.');
        }

        $this->container['tax_amount'] = $tax_amount;

        return $this;
    }

    /**
     * Gets capture
     *
     * @return bool|null
     */
    public function getCapture()
    {
        return $this->container['capture'];
    }

    /**
     * Sets capture
     *
     * @param bool|null $capture Set this to false if you only want to authorize for the amount. Defaults to true.
     *
     * @return self
     */
    public function setCapture($capture)
    {
        if (is_null($capture)) {
            throw new \InvalidArgumentException('non-nullable capture cannot be null');
        }
        $this->container['capture'] = $capture;

        return $this;
    }

    /**
     * Gets payment_method
     *
     * @return \TheLogicStudio\ExactPay\Foofoo\PaymentMethodChoice
     */
    public function getPaymentMethod()
    {
        return $this->container['payment_method'];
    }

    /**
     * Sets payment_method
     *
     * @param \TheLogicStudio\ExactPay\Foofoo\PaymentMethodChoice $payment_method payment_method
     *
     * @return self
     */
    public function setPaymentMethod($payment_method)
    {
        if (is_null($payment_method)) {
            throw new \InvalidArgumentException('non-nullable payment_method cannot be null');
        }
        $this->container['payment_method'] = $payment_method;

        return $this;
    }

    /**
     * Gets customer
     *
     * @return \TheLogicStudio\ExactPay\Foofoo\BillingCustomer|null
     */
    public function getCustomer()
    {
        return $this->container['customer'];
    }

    /**
     * Sets customer
     *
     * @param \TheLogicStudio\ExactPay\Foofoo\BillingCustomer|null $customer customer
     *
     * @return self
     */
    public function setCustomer($customer)
    {
        if (is_null($customer)) {
            throw new \InvalidArgumentException('non-nullable customer cannot be null');
        }
        $this->container['customer'] = $customer;

        return $this;
    }

    /**
     * Gets reference
     *
     * @return \TheLogicStudio\ExactPay\Foofoo\Reference|null
     */
    public function getReference()
    {
        return $this->container['reference'];
    }

    /**
     * Sets reference
     *
     * @param \TheLogicStudio\ExactPay\Foofoo\Reference|null $reference reference
     *
     * @return self
     */
    public function setReference($reference)
    {
        if (is_null($reference)) {
            throw new \InvalidArgumentException('non-nullable reference cannot be null');
        }
        $this->container['reference'] = $reference;

        return $this;
    }

    /**
     * Gets stored_credentials
     *
     * @return \TheLogicStudio\ExactPay\Foofoo\StoredCredentials|null
     */
    public function getStoredCredentials()
    {
        return $this->container['stored_credentials'];
    }

    /**
     * Sets stored_credentials
     *
     * @param \TheLogicStudio\ExactPay\Foofoo\StoredCredentials|null $stored_credentials stored_credentials
     *
     * @return self
     */
    public function setStoredCredentials($stored_credentials)
    {
        if (is_null($stored_credentials)) {
            throw new \InvalidArgumentException('non-nullable stored_credentials cannot be null');
        }
        $this->container['stored_credentials'] = $stored_credentials;

        return $this;
    }

    /**
     * Gets soft_descriptor
     *
     * @return \TheLogicStudio\ExactPay\Foofoo\SoftDescriptor|null
     */
    public function getSoftDescriptor()
    {
        return $this->container['soft_descriptor'];
    }

    /**
     * Sets soft_descriptor
     *
     * @param \TheLogicStudio\ExactPay\Foofoo\SoftDescriptor|null $soft_descriptor soft_descriptor
     *
     * @return self
     */
    public function setSoftDescriptor($soft_descriptor)
    {
        if (is_null($soft_descriptor)) {
            throw new \InvalidArgumentException('non-nullable soft_descriptor cannot be null');
        }
        $this->container['soft_descriptor'] = $soft_descriptor;

        return $this;
    }

    /**
     * Gets level3
     *
     * @return \TheLogicStudio\ExactPay\Foofoo\Level3|null
     */
    public function getLevel3()
    {
        return $this->container['level3'];
    }

    /**
     * Sets level3
     *
     * @param \TheLogicStudio\ExactPay\Foofoo\Level3|null $level3 level3
     *
     * @return self
     */
    public function setLevel3($level3)
    {
        if (is_null($level3)) {
            throw new \InvalidArgumentException('non-nullable level3 cannot be null');
        }
        $this->container['level3'] = $level3;

        return $this;
    }

    /**
     * Gets three_d_secure
     *
     * @return \TheLogicStudio\ExactPay\Foofoo\ThreeDSecure|null
     */
    public function getThreeDSecure()
    {
        return $this->container['three_d_secure'];
    }

    /**
     * Sets three_d_secure
     *
     * @param \TheLogicStudio\ExactPay\Foofoo\ThreeDSecure|null $three_d_secure three_d_secure
     *
     * @return self
     */
    public function setThreeDSecure($three_d_secure)
    {
        if (is_null($three_d_secure)) {
            throw new \InvalidArgumentException('non-nullable three_d_secure cannot be null');
        }
        $this->container['three_d_secure'] = $three_d_secure;

        return $this;
    }

    /**
     * Gets options
     *
     * @return \TheLogicStudio\ExactPay\Foofoo\PaymentOptions|null
     */
    public function getOptions()
    {
        return $this->container['options'];
    }

    /**
     * Sets options
     *
     * @param \TheLogicStudio\ExactPay\Foofoo\PaymentOptions|null $options options
     *
     * @return self
     */
    public function setOptions($options)
    {
        if (is_null($options)) {
            throw new \InvalidArgumentException('non-nullable options cannot be null');
        }
        $this->container['options'] = $options;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


